### ISSUE TITLE
onStepProgress seems to fire only on enter and exit

### ISSUE THREAD

**Issue by devanflaherty** [russellgoldenberg/scrollama#36]
I'm wanting to use Scrollama to parallax some elements over the progress of a div.

I've used ScrollMagic and looking to use Scrollama. Right now I just want to simply transform:translate an element on the progress of a step. The trigger step is the header of the page.

Here is some code below:

``` javascript
  function handleStepProgress(response) {
      console.log(response.progress)
  }

  function init() {
	scroller.setup({
	  step: '.step-parent .step',
          progress: true,
          offset: 0,
	  debug: true,
	})
	.onStepProgress(handleStepProgress)
	  window.addEventListener('resize', scroller.resize)
}
```

``` html
<section id="container">
    <div class="step-parent">
      <section class="step hero team-hero is-large"></section>
    </div>
</section>
```

``` CSS
.step-parent{
  background-color: black;
  position: relative;
  overflow: hidden;
  min-height: 400px;
}
.step {
  background-size: cover;
  background-position: center;
}
```

Any help or ways to better understand would be awesome.
